METHOD_NAME: 'Res101IBN*+CLIP-B_OMG2a_1e-4'  # “*”代表更新了视觉模型的Track1训练数据

TRAIN:
  MAX_EPOCH: 1000
  ONE_EPOCH_REPEAT: 1
  BATCH_SIZE: 32
  BASE_LR: 1e-4
  WARMUP_EPOCH: 500
  WARMUP_START_LR: 1e-6

MODEL:
  USE_SINGLE_TEXT: True
  USE_COLOR_TYPE: True
  USE_BIGGER_IMAGE: True
  ENCODER_TEXT: 'CLIP_ViT-B/32'
  ENCODER_IMG: 'r101ibn'