METHOD_NAME: 'Res50IBN+BERT_OMG1_NLAug'

TRAIN:
  MAX_EPOCH: 1000
  ONE_EPOCH_REPEAT: 1
  BATCH_SIZE: 32
  BASE_LR: 1e-3
  WARMUP_EPOCH: 500
  WARMUP_START_LR: 1e-5

DATA:
  NLAUG: True

MODEL:
  USE_SINGLE_TEXT: True