METHOD_NAME: 'Res50IBN+BERT_OMGb_c4'

TRAIN:
  MAX_EPOCH: 1000
  ONE_EPOCH_REPEAT: 1
  BATCH_SIZE: 16  # 32
  BASE_LR: 5e-4  # 1e-3
  WARMUP_EPOCH: 500
  WARMUP_START_LR: 5e-6  # 1e-5

MODEL:
  USE_BIGGER_IMAGE: True
  USE_FgMOTION: True