METHOD_NAME: 'Res50IBN+BERT_OMG2'

TRAIN:
  MAX_EPOCH: 1000
  ONE_EPOCH_REPEAT: 1
  BATCH_SIZE: 32
  BASE_LR: 1e-3
  WARMUP_EPOCH: 500
  WARMUP_START_LR: 1e-5

MODEL:
  USE_SINGLE_TEXT: True
  USE_COLOR_TYPE: True