METHOD_NAME: 'Res50IBN+CLIP-B_OMG2a_NLAug_IDLoss'

TRAIN:
  MAX_EPOCH: 1000
  ONE_EPOCH_REPEAT: 1
  BATCH_SIZE: 32
  BASE_LR: 1e-4  # 1e-3
  WARMUP_EPOCH: 500
  WARMUP_START_LR: 1e-5

MODEL:
  USE_SINGLE_TEXT: True
  USE_COLOR_TYPE: True
  USE_BIGGER_IMAGE: True
  ENCODER_TEXT: 'CLIP_ViT-B/32'
  ID_LOSS: True

DATA:
  NLAUG: True