METHOD_NAME: 'Swin-B+CLIP-B_OMG2a_NLAug_IDLoss_Continue'  # 用于在已有模型基础上继续微调训练

TRAIN:
  MAX_EPOCH: 100  # 600  # 1000
  ONE_EPOCH_REPEAT: 1
  BATCH_SIZE: 24  # 32
  BASE_LR: 1e-4  # 0.67e-3  # 1e-3
  WARMUP_EPOCH: 0  # 300  # 500
  WARMUP_START_LR: 1e-6  # 0.67e-5  # 1e-5

MODEL:
  USE_SINGLE_TEXT: True
  USE_COLOR_TYPE: True
  USE_BIGGER_IMAGE: True
  ENCODER_TEXT: 'CLIP_ViT-B/32'
  ENCODER_IMG: 'SwinTransformer'
  ID_LOSS: True

DATA:
  NLAUG: True
  SIZE: 384